{"data":{
"name":"شائع",
"categories":[{"id":181,
"name":"تأثيرات ضوئية",
"icon":"http://asia.badambiz.com/skin_X_1637658253474.png",
"remark":"LED光感动效皮肤",
"top_skins":[{
"name":"skin_led_zj_2",
"title":"ازرار متوهجه",
"author":"ziipin",
"info":"LED光感动效皮肤_指尖波纹_彩虹色_1",
"publish_time":1637312371,
"url":"http://ime-emotion-mde-zl.badambiz.com/skin_skin_skin_led_zj_2_1637312371443.zip",
"update_url":"",
"preview_url":"http://ime-emotion-mde-zl.badambiz.com/skin_preview_preview_1637312371226.png",
"ver_code":1,"ver_name":"1.0",
"position":2,"skin_type":1,"has_sound":false,"has_move":false,"vip_only":false,"area":"[\"all\"]",
"url_convert":["https://asia.badambiz.com/",
"https://ime-emotion-mde-zl.badambiz.com/"]},
{"name":"skin_led_LD_2",
"title":"ترددات ضوئية",
"author":"ziipin",
"info":"LED光感动效皮肤_雷达光效_彩虹色_1",
"publish_time":1637312329,"url":"https://asia.badambiz.com/skin_skin_skin_led_LD_2_1637312328268.zip",
"update_url":"",
"preview_url":"https://asia.badambiz.com/skin_preview_preview_1637312329989.png",
"ver_code":1,"ver_name":"1.0",
"position":1,"skin_type":1,"has_sound":false,"has_move":false,"vip_only":false,"area":"[\"all\"]",
"url_convert":["https://asia.badambiz.com/",
"https://ime-emotion-mde-tx.badambiz.com/"]},
{"name":"skin_ying_fire",
"title":"نسر الجليد والنار",
"author":"ziipin",
"info":"雄鹰",
"publish_time":1676520099,"url":"http://ime-emotion-mde-zl.badambiz.com/skin_skin_skin_ying_fire_1676520099095.zip",
"update_url":"",
"preview_url":"http://ime-emotion-mde-zl.badambiz.com/skin_X_1676520077571.gif",
"ver_code":1,"ver_name":"1.0",
"position":1207,"skin_type":1,"has_sound":false,"has_move":true,"vip_only":false,"area":"[\"all\"]",
"url_convert":["https://asia.badambiz.com/",
"https://ime-emotion-mde-zl.badambiz.com/"]}]}],
"total":20},"result":0}

